Sustituir la fila 0 de la matriz creada en el Ejercicio 1 por los valores (10, 20, 30, 40)

In [4]:
import numpy as np

In [5]:
a=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
a[0] = [10, 20, 30, 40]
print("Matriz modificada en fila 0:")
print(a)

Matriz modificada en fila 0:
[[10 20 30 40]
 [ 5  6  7  8]]
