Para la matriz creada en el Ejercicio 1 acceder a la fila Cero. Imprimir en pantalla el resultado.


In [1]:
import numpy as np

In [2]:
a=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8]])
print(a)


[[1 2 3 4]
 [5 6 7 8]]


In [3]:
print("Fila Cero:")
print(a[0])

Fila Cero:
[1 2 3 4]
