Crear una matriz de 2X3 con ceros utilizando la librería de Numpy
Nota: para este ejercicio podemos utilizar la función Zeros(). Probar crear
una nueva matriz con la función ones() y ver qué sucede.
Para ambos casos utilizar la función print para validar la matriz.

In [1]:
import numpy as np

In [2]:
# Matriz con ceros
matriz_ceros = np.zeros((2, 3))
print("Matriz de ceros:")
print(matriz_ceros)

# Matriz con unos
matriz_unos = np.ones((2, 3))
print("\nMatriz de unos:")
print(matriz_unos)

Matriz de ceros:
[[0. 0. 0.]
 [0. 0. 0.]]

Matriz de unos:
[[1. 1. 1.]
 [1. 1. 1.]]
