Utilizando la librería de Numpy crear una matriz identidad utilizando la función eyes().


In [2]:
import numpy as np

In [3]:
matriz_identidad = np.eye(3)
print("Matriz Identidad:")
print(matriz_identidad)

Matriz Identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
