Modificar el elemento de la fila 1 columna 0 y colocar el valor 10.

In [1]:
import numpy as np

In [2]:
a=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
a[1, 0] = 10
print("Matriz modificada en fila 1, columna 0:")
print(a)

Matriz modificada en fila 1, columna 0:
[[ 1  2  3  4]
 [10  6  7  8]]
